%YAML:1.0

TYPE: 'euroc'
SETTING: 'code/Examples/Monocular/EuRoC.yaml'
IMAGES: ['/dataset/MH_01_easy/mav0/cam0/data']
TIMES: ['code/Examples/Monocular/EuRoC_TimeStamps/MH01.txt']

# ID dispatch address and port
HOST: '0.0.0.0'
PORT: "10088"
